### ISSUE TITLE
Error when listing tracks in the 0.5 branch

### ISSUE THREAD

**Issue by pablorusso** [fuzeman/Spotify2.bundle#19]
When trying to list tracks: using starred menu, when accesing a playlist content or using the search box; it just keep spinning without showing anything.

In Log I have:

```
2014-05-17 16:53:05,580 (7f2dc51d6700) :  WARNING (logging_handler:18) - [pyemitter] Exception raised in callback <function on_playlist at 0x2a6a8c0> for event "success" - Traceback (most recent call last):
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Spotify2.bundle/Contents/Libraries/Shared/pyemitter.py", line 149, in __call_sync
    callback(*args, **kwargs)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Spotify2.bundle/Contents/Code/host.py", line 125, in on_playlist
    callback(self.containers.playlist(playlist))
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Spotify2.bundle/Contents/Code/containers.py", line 72, in playlist
    oc.add(self.objects.track(track))
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Spotify2.bundle/Contents/Code/objects.py", line 75, in track
    key=self.track_url(track),
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Spotify2.bundle/Contents/Code/objects.py", line 104, in track_url
    return function_path('play', uri=track.uri, ext='mp3')
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Spotify2.bundle/Contents/Code/routing.py", line 41, in function_path
    'function_args': pack(kwargs)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Spotify2.bundle/Contents/Code/routing.py", line 13, in pack
    serialized_obj = cerealizer.dumps(obj)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/cerealizer/__init__.py", line 683, in dumps
    Dumper().dump(obj, s)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/cerealizer/__init__.py", line 169, in dump
    self.collect(root_obj)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/cerealizer/__init__.py", line 213, in collect
    handler.collect(obj, self)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/cerealizer/__init__.py", line 398, in collect
    for i in obj.itervalues(): dumper.collect(i)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/cerealizer/__init__.py", line 212, in collect
    if not handler: raise NonCerealizableObjectError("Object of class/type '%s' cannot be cerealized! Use cerealizer.register to extend Cerealizer support to other classes." % obj.__class__)
NonCerealizableObjectError: Object of class/type '<class 'spotify.core.uri.Uri'>' cannot be cerealized! Use cerealizer.register to extend Cerealizer support to other classes.

2014-05-17 16:53:13,283 (7f2da77fe700) :  DEBUG (runtime:918) - Response: [200] MessageContainer, 163 bytes
2014-05-17 16:53:33,768 (7f2da6ffd700) :  DEBUG (runtime:918) - Response: [200] MessageContainer, 163 bytes
```
- Plex last version for Linux (Ubuntu server)
- Client web and iOS (same result both)

BTW, the master branch works without problems with the same setup.

**Comment by fuzeman** [comment]
I'm guessing you disabled the "Proxy tracks (via PMS)" option?

Currently the beta branch only supports serving tracks via Plex Media Server (this is the most reliable method for streaming tracks). I'll possibly have "direct" streaming available in a future beta release.
