### ISSUE TITLE
Unable to login (log attached, premium account, Plex on Windows 8.1)

### ISSUE THREAD

**Issue by Jaedee** [fuzeman/Spotify2.bundle#37]
Username and password are definitely correct. Plugin appears fine in the web client, after entering username and password correctly I am presented with three options:
1. Explore
2. Your Music
3. About

About - reports version as 0.5.5 and show credits correctly.

Both Explore and Your Music present with login failed.

Logs:

```
2014-07-28 22:03:17,933 (16cc) :  DEBUG (runtime:717) - Handling request GET /music/spotify
2014-07-28 22:03:17,934 (16cc) :  DEBUG (runtime:814) - Found route matching /music/spotify
2014-07-28 22:03:17,934 (16cc) :  DEBUG (logkit:13) - plugin_callback - method: <unbound method SpotifyHost.main_menu>, kwargs: {}, async: False
2014-07-28 22:03:17,937 (16cc) :  DEBUG (base:125) - Checking if com.plexapp.plugins.spotify2 is broken
2014-07-28 22:03:17,938 (16cc) :  DEBUG (networking:172) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.system/messaging/function/X1N0b3JlU2VydmljZTpJc0NoYW5uZWxCcm9rZW4_/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMQpzMjgKY29tLnBsZXhhcHAucGx1Z2lucy5zcG90aWZ5MnMxMAppZGVudGlmaWVycjAK'
2014-07-28 22:03:17,948 (16cc) :  DEBUG (runtime:918) - Response: [200] MediaContainer, 1231 bytes
2014-07-28 22:03:18,987 (1374) :  DEBUG (runtime:717) - Handling request GET /music/spotify
2014-07-28 22:03:18,989 (1374) :  DEBUG (runtime:814) - Found route matching /music/spotify
2014-07-28 22:03:18,989 (1374) :  DEBUG (logkit:13) - plugin_callback - method: <unbound method SpotifyHost.main_menu>, kwargs: {}, async: False
2014-07-28 22:03:18,992 (1374) :  DEBUG (base:125) - Checking if com.plexapp.plugins.spotify2 is broken
2014-07-28 22:03:18,993 (1374) :  DEBUG (networking:172) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.system/messaging/function/X1N0b3JlU2VydmljZTpJc0NoYW5uZWxCcm9rZW4_/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMQpzMjgKY29tLnBsZXhhcHAucGx1Z2lucy5zcG90aWZ5MnMxMAppZGVudGlmaWVycjAK'
2014-07-28 22:03:19,007 (1374) :  DEBUG (runtime:918) - Response: [200] MediaContainer, 1231 bytes
2014-07-28 22:03:19,332 (c4) :  DEBUG (runtime:717) - Handling request GET /music/spotify/your_music
2014-07-28 22:03:19,334 (c4) :  DEBUG (runtime:814) - Found route matching /music/spotify/your_music
2014-07-28 22:03:19,334 (c4) :  DEBUG (logkit:13) - plugin_callback - method: <decorator object at 0x04BD7CB0>, kwargs: {}, async: False
2014-07-28 22:03:19,334 (c4) :  DEBUG (logkit:13) - authenticated
2014-07-28 22:03:29,334 (c4) :  DEBUG (logkit:13) - authenticated - login error
2014-07-28 22:03:29,334 (c4) :  DEBUG (runtime:918) - Response: [200] MessageContainer, 152 bytes
2014-07-28 22:04:57,618 (df8) :  DEBUG (logkit:13) - [spotify.components.connection] send encoded: '{"args":["h"],"name":"sp/echo","id":"2"}'
2014-07-28 22:05:00,467 (13f4) :  INFO (logkit:16) - [spotify.components.connection] Spotify connection closed
2014-07-28 22:05:00,467 (13f4) :  DEBUG (logkit:13) - Last reconnection attempt was 183.542999983 seconds ago
2014-07-28 22:05:00,469 (13f4) :  INFO (logkit:16) - Attempting reconnection to Spotify...
2014-07-28 22:05:00,469 (13f4) :  INFO (logkit:16) - [spotify.client] Authenticating...
2014-07-28 22:05:00,471 (102c) :  INFO (logkit:16) - [requests.packages.urllib3.connectionpool] Resetting dropped connection: play.spotify.com
2014-07-28 22:05:00,690 (102c) :  DEBUG (logkit:13) - [requests.packages.urllib3.connectionpool] "GET / HTTP/1.1" 200 None
2014-07-28 22:05:00,693 (102c) :  DEBUG (logkit:13) - [spotify.components.authentication] Landing - success, code: 200, content-type: text/html
2014-07-28 22:05:00,696 (102c) :  DEBUG (logkit:13) - [spotify.components.authentication] Landing - CSRF token: d8d82dcab1e59972b4f00fda9ed81cb3, tracking ID: 852cdbd3f9cf265b931fec67ece6a42d43ac31c9
2014-07-28 22:05:00,752 (102c) :  DEBUG (logkit:13) - [requests.packages.urllib3.connectionpool] "POST /xhr/json/auth.php HTTP/1.1" 200 None
2014-07-28 22:05:00,753 (102c) :  DEBUG (logkit:13) - [spotify.components.authentication] Authenticate - success, code: 200, content-type: application/json; charset=utf-8
2014-07-28 22:05:00,762 (102c) :  INFO (logkit:16) - [spotify.client] Connecting...
2014-07-28 22:05:00,762 (102c) :  DEBUG (logkit:13) - [spotify.client] ap resolver: {u'override': None, u'hostname': u'apresolve.spotify.com', u'site': None}
2014-07-28 22:05:00,806 (102c) :  DEBUG (logkit:13) - [requests.packages.urllib3.connectionpool] "GET /?client=24%3A0%3A0%3A62300317 HTTP/1.1" 200 None
2014-07-28 22:05:00,808 (102c) :  DEBUG (logkit:13) - [spotify.client] ap resolver - success, code: 200, content-type: application/json; charset=utf-8
2014-07-28 22:05:00,808 (102c) :  DEBUG (logkit:13) - [spotify.client] Selected AP at "wss://lon2-linkap-a2.ap.spotify.com:443/"
2014-07-28 22:05:00,825 (102c) :  INFO (logkit:16) - [spotify.components.connection] Connecting to "wss://lon2-linkap-a2.ap.spotify.com:443/"
2014-07-28 22:05:00,924 (179c) :  DEBUG (logkit:13) - [spotify.components.connection] WebSocket "open" event
2014-07-28 22:05:00,926 (179c) :  DEBUG (logkit:13) - [spotify.components.connection] send_connect()
2014-07-28 22:05:00,926 (179c) :  DEBUG (logkit:13) - [spotify.components.connection] send encoded: '{"args":["201","c43e9479d3716e57259f44ac2f74ba7ca30892bb","{\\"ip\\":\\"2.99.148.255\\",\\"timestamp\\":1406581499,\\"ttl\\":900,\\"useragent\\":\\"Mozilla\\\\/5.0 (Windows NT 6.3; WOW64) AppleWebKit\\\\/537.36 (KHTML, like Gecko) Chrome\\\\/36.0.1941.0 Safari\\\\/537.36\\",\\"version\\":62300317,\\"token\\":\\"NApkCkwKDVNwb3RpZnktdXNlcnMSDWNhdHNoYXZldGVhdHMaA5gBASV_vtZTMiIKCHzDRJUbL5W-Ehb528HUw1vAXKx-vFfrPu8ZZT2H-8LcEhQ8qS8PeXqvW0JFfIcq368CXyj_ZA\\"}"],"name":"connect","id":"0"}'
2014-07-28 22:05:00,983 (179c) :  DEBUG (logkit:13) - [spotify.components.connection] SpotifyConnection "connect" event: {u'id': 0, u'result': u'ok'}
2014-07-28 22:05:00,984 (179c) :  DEBUG (logkit:13) - [spotify.components.connection] connected
2014-07-28 22:05:00,986 (d0) :  DEBUG (logkit:13) - [spotify.commands.work] got work, payload: var t2; try { var d = new Date(); t2 = ('d'[(35725129862..toString(36<<0))[0]])(); } catch(_) { t2 = 35725129862..toString(36<<0); };this.reply('' + t2);
2014-07-28 22:05:00,990 (99c) :  DEBUG (logkit:13) - [spotify.commands.flash] received ping [u'87', u'0', u'10', u'170', u'209', u'198', u'31', u'2', u'2', u'46', u'204', u'92', u'223', u'196', u'242', u'248', u'104', u'129', u'135', u'255'], sending pong: 144 151 44 194 126 215 173 31 7 49
2014-07-28 22:05:00,990 (99c) :  DEBUG (logkit:13) - [spotify.components.connection] send encoded: '{"args":["144 151 44 194 126 215 173 31 7 49"],"name":"sp/pong_flash2","id":"1"}'
2014-07-28 22:05:01,069 (d0) :  WARNING (logkit:19) - [spotify.commands.work] Unable to run work -  - Traceback (most recent call last):
  File "C:\Users\Jaydee\AppData\Local\Plex Media Server\Plug-ins\Spotify2.bundle\Contents\Libraries\Shared\spotify\commands\work.py", line 32, in process
    result = ctx.eval('main.run.call(main)')
  File "C:\Users\Jaydee\AppData\Local\Plex Media Server\Plug-ins\Spotify2.bundle\Contents\Libraries\Shared\execjs\__init__.py", line 239, in eval
    return self.exec_(code, options=options)
  File "C:\Users\Jaydee\AppData\Local\Plex Media Server\Plug-ins\Spotify2.bundle\Contents\Libraries\Shared\execjs\__init__.py", line 250, in exec_
    output = self._runtime._execfile(filename)
  File "C:\Users\Jaydee\AppData\Local\Plex Media Server\Plug-ins\Spotify2.bundle\Contents\Libraries\Shared\execjs\__init__.py", line 225, in _execfile
    raise RuntimeError(stdoutdata)
RuntimeError
```

**Comment by fuzeman** [comment]
This appears to be a separate login issue from the current big issue I'm working on (#38). 

Installing node.js might fix this (the RuntimeError, login will still end up failing), otherwise I'll need to come back to this once issue #38 has been resolved.

**Comment by Jaedee** [comment]
You were quite right, installation of node.js did indeed fix the RuntimeError.

Thanks for your continued support on the substantive issue, donated to your paypal earlier today as a measure of thanks.

**Comment by fuzeman** [comment]
Thanks for the donation - v0.5.6 should fix authentication now, could you check if login works for you now?

**Comment by Jaedee** [comment]
Can confirm, now works!

You're a star!

**Comment by FlyingPersian** [comment]
Hi
Not working over here on FreeNAS :/ Tried installing node.js via packagemanagern (pkg install node, v4.1.1), but still getting the error. Spotify2.bundle is version 0.5.8 and I tried both the version from the UnsupportedAppStore and the version here on github :/ Still getting the node.js error. Any ideas?

Edit: Login works fine.
